#+title: A Short and Informal Introduction of PBW theorem
#+CREATOR: Notes taken by Dendy Li

#+LATEX_HEADER: \input{~/Preamble/preamble.tex}
#+LATEX_COMPILER: xelatex

# * Tensor Product
# Here's a example of tensor product in low dimension:
# Let \( V:=\R^2 \), the tensor product of \( V \) is just the

* Preliminary
** Topological groups
#+ATTR_LATEX: :options [Topological space]
#+BEGIN_definition
A topological space is a set \(X\) together with a set of subsets \(U \subset X\), called open sets, satisfies the following two operation:
+ finite intersections
+ arbitrary unions
#+END_definition

#+ATTR_LATEX: :options [Topological groups]
#+BEGIN_definition
A topological groups is:
- a group
  + Set \(G\)
  + Identity \(e\in G\)
  + Associative unital function \(f \cdot f\)
  + Inverse function \(f^{-1}\)Two elements's image under associative unital function is the neutral element)
- a topology given on the power set of \(G\), s.t. \(f \cdot f \) and \(f^{-1}\) are continuous functions w.r.t the given topology and the product topology(The latter).
#+END_definition


*Basic ideas of the continuous map: A map is a continuous map if its value do not jump with variation of its argument.*

#+ATTR_LATEX: :options [continuous functions (In topological spaces)]
#+BEGIN_definition
\(f: X \to Y\) is a continuous map(\(X,Y\) are topological spaces) if for every open subset \(U \subseteq Y\), the preimage \(f^{-1}(U)\) is an open subset of \(X\).
#+END_definition

Namely open set maps to open set, where the open sets lie in the given topology.

*Idea of connected: A topological space is connected if it can not be split up into two parts.*

#+ATTR_LATEX: :options [Smooth]
#+BEGIN_definition
We say a function is smooth if it can be differentiate for infinitely many times.
#+END_definition

#+ATTR_LATEX: :options [Closed subgroup]
#+BEGIN_definition
Let \(H,G\) be topological groups, \(H \subseteq G\) is closed if \(H\) is a closed subspace of \(G\) in topological sense.
#+END_definition

*Idea of closed map is just the analog of open map.*

#+ATTR_LATEX: :options [Closed map]
#+BEGIN_definition
A closed map is a map where closed set maps to the closed set.
#+END_definition

*Difference between closed map, open map and continuous map: Closed map and open map talks about where image goes and continuous map talks about where preimage goes.*

* Tensor Product and Tensor
** Informal introduction to Tensor
#+ATTR_LATEX: :options [Index set \(I_n\)]
#+BEGIN_definition
We can define the index set \( I_n := {1,2,\dots,n} \).
#+END_definition

eg. We can use the \( I_n \) we define above to express familiar object in a way that we are not familiat with.

#+ATTR_LATEX: :options [Sequence]
#+BEGIN_definition
A finite sequence \( \{a_k\}_{k = 1}^n \) on \( \R \) is a function:
\[
\{a_k\}_{k = 1}^n : I_n \to \R
\]
where \( \{a_k\}_{k = 1}^n(i) \mapsto a_i \).
#+END_definition

Similarly we can define matrix in a following way:
#+ATTR_LATEX: :options [Matrix]
#+BEGIN_definition
A matrix \( A \in \mathbb{R}^{m\times n} \) is a function:
\[
A : I_m \times I_n \to \R
\]
where \( A(i,j) \mapsto a_{ij} \).
#+END_definition

We can naturally deduce the definition of Tensor from the above convention:

#+ATTR_LATEX: :options [Tensor(Informally)]
#+BEGIN_definition
A Tensor \( T \) is a function:
\[
T : I_{m_1} \times I_{m_2} \times I_{m_k} \to \R (\forall k \in \Z)
\]
where \(T(i_1, i_2, \dots, i_k) \mapsto a_{i_1, i_2, \dots, i_k}\).
#+END_definition

Unfortunately the informal definition of the tensor isn't enough for us to detect enough infomations, one should add more details on the definition.

We first introduce the definition of the tensor product, then we define tensor as the element in the corresponding resulting vector space defined by tensor product.

We can give a formal way to express the idea above
** Tensor as Multidimensional arrays
** Tensor as Multilinear maps
** Categorical definition of Tensor Product
For vector space \(V, W\) the tensor product \(V \otimes W\) is the vector space generated by the elements of form \(v \otimes w\), satisfying the following universal property:
\begin{center}\begin{tikzcd}
V \times W \ar[r,"\phi"] \ar[rd,dashed,swap,"\psi"] & V \otimes W \ar[d,"\varphi"] \\
& \mathcal{T}
\end{tikzcd}\end{center}

Where \(\phi,\psi\) are bilinear maps and \(\varphi\) is linear map.

** Categorical definition of Tensor
** My Personal understanding of Tensor Product
We now stick to the \(\R\)-vector space \( V \) and \( W \), where \( V \) is of dimension \( n \) and \( W \) is of dimension \( m \).

We have the following convention:
- \( B_V \) denote the set of orthonormal bases of \( V \), a typical element in \( B_V \) is \( v_i \) which we represent by \(\begin{bmatrix} 0 \\ \vdots \\ 1_v \\ 0 \\ \vdots \\ 0 \end{bmatrix}\). \( B_W \) denote the set of orthonormal bases of \( W \), a typical element in \( B_W \) is \( w_i \) which we represent by \(\begin{bmatrix} 0 \\ \vdots \\ 1_w \\ 0 \\ \vdots \\ 0 \end{bmatrix}\)

- Here \( 1_v, 1_w \) denote the identity in the vector space \( V, W \) seperately. \( v_i \in \R^{n\times 1}\) and \(w_j \in \R^{m\times 1}\).

By the universal property of Tensor product we have the following diagram commute:
\begin{center}\begin{tikzcd}
V\times W \ar[r,"\phi"] \ar[rd, dashed, swap, "\psi"] & V \otimes W \ar[d,"\varphi"] \\
& \mathcal{T}
\end{tikzcd}\end{center}

Where \(\forall v \in V, \forall w \in W\), we have the following commutative diagram shows where the elements goes:

\begin{center}\begin{tikzcd}
(Span(v),Span(w)) \ar[r, mapsto] \ar[rd, mapsto] & Span(v) \otimes Span(w) \ar[d, mapsto] \\
& T_{v\otimes w}
\end{tikzcd}\end{center}

here \(Span(v), Span(w)\) represents the linear combination of \(v,w\) under the given orthonormal bases with coefficient in \( \R \).
* Lie Groups
*Lie group is a group also a manifold.*
*Basic convention: \(\R\) for real number with addition, \(\R^{\times}\) for non-zero real number with multiplication.

** Dimension 0 Lie groups
same as discrete groups

We can split any lie group into a connected part and a discrete part.

eg. \(R_{>0} \to \R^{\times} \to \{+,-\}\)

** Dimension 1 Lie groups
- \(\R\)
- \(\R^{\times}\)
- \(S^1\)

#+ATTR_LATEX: :options [Local Isomorphism(informal)]
#+BEGIN_definition
Near identity element the two groups are looks the same.
#+END_definition

** Dimension 2 Lie groups
- \(R^1 \times R^1\)
- \(R^1 \times S^1\)
- \(S^1 \times S^1\)
Any abelian connected Lie group \(\simeq R^m \times (S^1)^n\)

*First Non-abelian Lie group*
\(ax + b\) group

This is a solvable lie group.

#+ATTR_LATEX: :options [Solvable group]
#+BEGIN_definition
Group \(G\) is solvable is there is a chain of subgroups, every nearby component's quotient in the chain is abelian.
#+END_definition

** Dimension 3 Lie groups
*Most important Lie group*
- \(SL_2(\R)\)
  *Remark: This is dimension \(3\) because the \(2\times 2\) matrices are dimension \(4\), setting determinant to 1 reduce 1 dimension.*

#+ATTR_LATEX: :options [Nilpotent group]
#+BEGIN_definition
Let \(G_0\) be a group,
\[
G_i = G_{i-1}/center,
\]
if there exists \(n\), such that \(G_n = 1\), then \(G_0\) is called Nilpotent.
#+END_definition

** Connected & Closed
#+ATTR_LATEX: :options [Connected]
#+BEGIN_definition
We say a Lie group is connected if the Group's multiplication map and the inverse map are all smooth maps.
#+END_definition

#+ATTR_LATEX: :options [Closed]
#+BEGIN_definition
We
#+END_definition
* Lie Algebra
*Motivation: Lie groups is very complicated, so we use lie algebra to decribe lie group near the identity.*

Recall of manifold.

#+ATTR_LATEX: :options [\(1^{st}\) order differential operators]
#+BEGIN_definition
\(\Sigma f_i (x_1,\dots,x_n) \)
#+END_definition

#+ATTR_LATEX: :options [Vector fields]
#+BEGIN_definition
Geometric way to see \(1^{st}\) order differential operators.
#+END_definition

#+ATTR_LATEX: :options [Infinitesimal automorphisms]
#+BEGIN_definition
Vector field like an automorphism to move everything in a infinitly samll distence.
#+END_definition

** Define Lie Bracket
*Goal: How to put an algebraic structure on the \(1^{st}\) order differential operators?*

Consider the following process:
- Let \(D = \Sigma f_i, \ E = \Sigma g_i\)
- \(DE = \Sigma f_i \Sigma g_j\) by chain rule
- \(ED = \Sigma f_i \Sigma g_j\) by chain rule
- *Observe that \(DE\) and \(ED\) almost commute, and \(DE - ED\) is again a \(1^st\) order operator, this leads to the definition of lie bracket.*
- Define lie bracket of \([D,E] = DE - ED\).

  *Next we consider what identity satisfies by \([D,E]\)?(not to find the identity element)*

  - \([D,E] = -[E,D]\)
  - Jacobi Identity
  -

*Check of Jacobi Identity:*
#+ATTR_LATEX: :options [Check of Jacobi Identity]
#+BEGIN_proof
\leavevmode

wts: \([[A,B],C] + [[B,C],A] + [[C,A],B] = 0 \)

\begin{align}
[[A,B],C] + [[B,C],A] + [[C,A],B]
&= [AB - BA, C] + [BC - CB, A] + [CA - AC, B] \\
&= (AB - BA)C - C(AB - BA) + (BC - CB)A - A(BC - CB) \nonumber \\
&\quad + (CA - AC)B - B(CA - AC) \\
&= ABC - BAC - CAB + CBA + BCA - CBA \nonumber \\
&\quad - ABC + ACB + CAB - ACB - BCA + BAC \\
&= 0
\end{align}

#+END_proof


#+ATTR_LATEX: :options [Lie Algebra]
#+BEGIN_definition
A Lie Algebra \(L\) is a vector space over a field \(F\) with an additional operation(Lie Bracket) \(L \times L \to L\). This operation satisfies the following properties
+ Bilinear
+ \([xx]\) = 0 for all \(x\) in \(L\)
+ \([x[yz]] + [y[zx]] + [z[xy]] =  0\) for all \(x,y,z \in L\)
#+END_definition

** Find the lie algebra of a lie group
*** Abstract Way
Look at the vector field on \(G\), to be concrete *Left-invariant vector field*.

Why left-invariant vector field?
Left-invariant vector field is uniquely determined by the identity. In this case corresponds to the tangent vectors at identity.

We consider \(G\) acts on \(G\) by left translation.

By definition left-invariant vector fields closed under lie-bracket.

How to do it?
Take a tangent vector at the identity, make it to a left-invariant vector fields, calculate the lie bracket of them and restrict back to the identity.

*** Compute some trivial case
Let \(G = \R^n\) under addition,
- Left invariant vector fields: \(\Sigma a_i\).
- \([,] = 0\).

Let \(G = GL_n(\R)\),
- Lie algebra corresponding to \(M_n(\R)\)

How a matrix in \(M_n(\R)\) corresponds to a vector field and why the lie bracket operation matches?

Lie bracket and the commutator of the group

Hall-Witt identity and Jacobi Identity

* Tensor Algebra and Symmetric Algebra
** Tensor Algebra
#+ATTR_LATEX: :options [Tensor Algebra]
#+BEGIN_definition
Informally, tensor algebra can be viewed as a direct sum of vecter spaces which is also a vector space.
#+END_definition

Next we show how to construct a Tensor Algebra \(T(V)\) out of a vector space \(V\).

#+ATTR_LATEX: :options [Tensor Algebra of degree \(i\)]
#+BEGIN_definition
We denote Tensor Algebra of degree \(i\) on vector space \(V\) over field \(F\) as \(T^iV\), which is the tensor product of \(V\) takes \(i\) times, namely
\[
T^iV := \bigotimes\limits_{k = 1}^iV
\]
we define \(T^0V = F\).
#+END_definition

Using the above notation we can define the Tensor Algebra \(T(V) = \bigoplus\limits_{i = 0}^{\infty} T^iV\).

Next we construct the symmetric algebra out of the tensor algebra(\(T(V)\)) on vector space \(V\) of the field \(F\).

** Symmetric Algebra
#+ATTR_LATEX: :options ["Force Commutative" ideal \(\mathfrak{b}\)]
#+BEGIN_definition
In \(T^iV\), we define \(\mathfrak{b}_i\) be the ideal generated by all the element of form
\[
x_1 \otimes \cdots \otimes x_i - x_{\sigma(1)} \otimes \cdots \otimes x_{\sigma(i)}
\]
here \(\sigma\) is any permutation on \({1,2,\dots,i}\).
#+END_definition

#+ATTR_LATEX: :options [Symmetric Algebra of degree \(i\)]
#+BEGIN_definition
We define symmetric algebra of degree \(i\) as follows
\[
S^iV = T^iV / \mathfrak{b}_i
\]
#+END_definition

By analog we define the Symmetric Algebra on vector space \(V\) as follows
#+ATTR_LATEX: :options [Symmetric Algebra on vector space \(V\)]
#+BEGIN_definition
We denote symmetric algebra on vector space \(V\) on field \(F\) as \(S(V)\), which is defined as follows
\[
S(V) := \bigoplus\limits_{i = 0}^{\infty} S^iV
\]
#+END_definition

* Universal Enveloping Algebra and PBW theorem
** Universal Enveloping Algebra
Since Lie Algebra\(L\) is a vector space so we can natural construct the tensor algebra\((T(L)\)and the symmetric algebra \(S(L)\).

The goal of the PBW theorem is to show the isomorphism between \(S(L)\) and an "Universal enveloping algebra \(U(L)\)" which connect with the Lie Algebra \(L\) by a canonical map induced by the bracket operation in the Lie Algebra(i.e. \(L\) can be embedding in \(U(L)\) by a canonical map \(i\), where \(i\) is a linear map satisfies \(i([xy]) = i(x)i(y) - i(y)i(x)\)).

Now we construct the Universal enveploping algebra \(U(L)\) on the Lie Algebra \(L\) over the field \(F\), where
\[
U(L):= T(L)/\sim
\]
here ~ represents the relation \(x \sim y\) if \(x,y\) satisfies \(i([xy]) = i(x)i(y) - i(y)i(x)\), one can also think of ~ as the ideal generated by the element \(x \otimes y - y \otimes x - [xy]\).

This construction above shows the existence of \(U(L)\). \(U(L)\) also has the universal property to insure the uniqueness of \((U(L),i)\), i.e. if we have another pair \((U^{\prime},i^{\prime})\) then there is an isomorphism between the two pairs.

** PBW theorem
Once we have the PBW theorem, we have \(L \to U(L) \simeq S(L)\). This shows the idea in the front of the chapter where we can associate the Lie algebra \(L\) to an associative algebra(i.e.\(U(L)\)) which is generated as "freely" as possible by the commutation relations(relation ~ above).

** Proof of PBW theorem
*Goal: \(U(L)\) is the same size of the polynomial algebra on \(n\) variables where \(n = dim(L)\).*

*** Part I-Find the "upper bound" of the universal enveloping algebra (Symmetric Algebra \(\to\) Universal enveloping Algebra is onto)

#+ATTR_LATEX: :options [Universal enveloping algebra characterisation]
#+BEGIN_definition
We denote the universal enveloping algebra generated by lie algebra \(L\) by \(U(L)\). This is an associative algebra generated by \(L\), with the following correspondence:
- \(L \to U(L)\)
- \(a \to a\)
- \(b \to b\)
- \([a,b] \to ab - ba\)
#+END_definition

We go through some example to get familiar with the concept.
eg:
- Let \(L\) abelian, \([a,b] = 0\), with basis \(a_1,\dots,a_n\), then \(U(L)\) in this case is just \(\R[a_1,\dots,a_n]\).
- Let \(L\) spanned by \(a,b, [a,b] = b\), then \(U(L)\) generated by \(a,b\) with \(ab - ba = b\).


*For Lie algebra \(L\), pick its basis \(a_1, a_2, \dots, a_n\), then by the convention before \(U(L)\) is spanned by \(a_{i_1}, a_{i_2}, \dots, a_{i_k}\).*

More information should be added to show why we can arrange \(a_{i_1}, a_{i_2}, \dots, a_{i_k}\) in an increasing order.

*** Part II-Find the lower bound of the universal enveloping algebra.
